# Generated by Django 5.2.6 on 2025-10-02 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del viaje', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción del viaje')),
                ('start_date', models.DateField(help_text='Fecha de ida')),
                ('end_date', models.DateField(help_text='Fecha de vuelta')),
                ('origin', models.CharField(help_text='Ciudad de origen', max_length=100)),
                ('destination', models.CharField(help_text='Ciudad de destino', max_length=100)),
                ('travel_style', models.CharField(choices=[('mochilero', 'Mochilero'), ('relax', 'Relax'), ('aventura', 'Aventura'), ('cultural', 'Cultural'), ('gastronomico', 'Gastronómico'), ('naturaleza', 'Naturaleza')], help_text='Estilo de viaje', max_length=20)),
                ('transport_type', models.CharField(choices=[('auto', 'Auto'), ('colectivo', 'Colectivo'), ('avion', 'Avión'), ('tren', 'Tren'), ('barco', 'Barco'), ('combinado', 'Combinado')], help_text='Tipo de transporte', max_length=20)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('airbnb', 'Airbnb'), ('camping', 'Camping'), ('casa', 'Casa'), ('combinado', 'Combinado')], help_text='Tipo de hospedaje', max_length=20)),
                ('planned_activities', models.TextField(blank=True, help_text='Actividades previstas')),
                ('max_participants', models.PositiveIntegerField(default=2, help_text='Cantidad máxima de personas')),
                ('current_participants', models.PositiveIntegerField(default=1, help_text='Cantidad actual de participantes')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto mínimo', max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto máximo', max_digits=10, null=True)),
                ('flexibility_level', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', help_text='Nivel de flexibilidad', max_length=10)),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='abierto', help_text='Estado del viaje', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('withdrawn', 'Retirada')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Mensaje del aplicante al anfitrión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('trip', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_creator', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
