# Generated by Django 5.2.6 on 2025-10-15 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('trip_created', 'Viaje Creado'), ('trip_joined', 'Usuario se unió a viaje'), ('application_received', 'Nueva aplicación recibida'), ('application_accepted', 'Aplicación aceptada'), ('application_rejected', 'Aplicación rechazada'), ('friendship_request', 'Solicitud de amistad'), ('friendship_accepted', 'Amistad aceptada'), ('trip_completed', 'Viaje completado'), ('trip_reviewed', 'Viaje reseñado'), ('user_joined', 'Nuevo usuario se registró')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to='trips.application')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_feed_events', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='trips_feede_event_t_d86827_idx'), models.Index(fields=['user', 'created_at'], name='trips_feede_user_id_e95e68_idx'), models.Index(fields=['is_public', 'created_at'], name='trips_feede_is_publ_a3b38c_idx')],
            },
        ),
    ]
